version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/bottleneckco/discord-radio
    environment:
      GO111MODULE: 'on'
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod download
      - run: go build -a -o discord-radio-linux64 .
      # - run: env GOOS=linux GOARCH=386 go build -a -o discord-radio-linux32 .
      # - run: env GOOS=windows GOARCH=386 go build -a -o discord-radio-win32.exe .
      - run: env GOOS=windows GOARCH=amd64 go build -a -o discord-radio-win64.exe .
      - run: env GOOS=darwin GOARCH=amd64 go build -a -o discord-radio-darwin .
      - persist_to_workspace:
          root: .
          paths:
            - discord-radio-*
  deploy:
    docker:
        - image: circleci/golang:1.12
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete "${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}" ./artifacts/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
