version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.4
    working_directory: /go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout:
        path: /go/src/github.com/$CIRCLE_PROJECT_USERNAME

      # specify any bash command here prefixed with `run: `
      - run: dep ensure -vendor-only
      - run: go build -a -o $CIRCLE_PROJECT_REPONAME .
