version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.4
    working_directory: /go/src/github.com/bottleneckco/radio-clerk
    steps:
      - checkout:
          path: /go/src/github.com/bottleneckco

      # specify any bash command here prefixed with `run: `
      - run: pwd
      - run: dep ensure -vendor-only
      - run: go build -a -o $CIRCLE_PROJECT_REPONAME .
