version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.4
    working_directory: /go/src/github.com/bottleneckco/radio-clerk
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: dep ensure -vendor-only
      - run: go build -a -o radio-clerk .
      - persist_to_workspace:
          root: .
          paths:
            - radio-clerk
  deploy:
    docker:
        - image: ruby:2.5
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: gem install dpl
      - run: dpl --provider=releases --repo=bottleneckco/radio-clerk "--release-number=$CIRCLE_BRANCH-$CIRCLE_SHA1-$CIRCLE_BUILD_NUM" --api-key=$GITHUB_TOKEN --file=radio-clerk --prerelease
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: add-ci